-- MySQL Script generated by MySQL Workbench
-- Thu Aug 10 21:19:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Caja_menor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caja_menor` (
  `Nit` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(100) NOT NULL,
  `Correo_Electronico` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Nit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `Id_Empresa` INT NOT NULL AUTO_INCREMENT,
  `Nit` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(100) NOT NULL,
  `Correo_Electronico` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id_Empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `Id_Empresa` INT NOT NULL AUTO_INCREMENT,
  `Gerente` VARCHAR(100) NOT NULL,
  `Administrador` VARCHAR(100) NULL,
  `Colaborador` VARCHAR(100) NULL,
  PRIMARY KEY (`Id_Empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gerente` (
  `Id_Gerente` INT NOT NULL AUTO_INCREMENT,
  `Numero_Documento` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(100) NOT NULL,
  `Correo_Electronico` VARCHAR(100) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `Id_Administrador` INT NOT NULL AUTO_INCREMENT,
  `Numero_Documento` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(100) NOT NULL,
  `Correo_Electronico` VARCHAR(100) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Colaborador` (
  `Id_Colaborador` INT NOT NULL AUTO_INCREMENT,
  `Numero_Documento` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(100) NOT NULL,
  `Correo_Electronico` VARCHAR(100) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingreso_Caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingreso_Caja` (
  `Id_Ingreso_Caja` INT NOT NULL AUTO_INCREMENT,
  `Documento` INT NOT NULL,
  `Valor_Ingreso` INT NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Detalle` VARCHAR(200) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Adjuntar_archivo` VARCHAR(100) NULL,
  PRIMARY KEY (`Id_Ingreso_Caja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Egreso_Caja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Egreso_Caja` (
  `Id_Egreso_Caja` INT NOT NULL AUTO_INCREMENT,
  `Documento` INT NOT NULL,
  `Valor_Ingreso` INT NOT NULL,
  `Direccion` VARCHAR(100) NOT NULL,
  `Detalle` VARCHAR(200) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Adjuntar_archivo` VARCHAR(100) NULL,
  `Tipo_Egreso` VARCHAR(100) NULL,
  `Tipo_Documento` VARCHAR(100) NULL,
  PRIMARY KEY (`Id_Egreso_Caja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Eventos` (
  `Id_Evento` INT NOT NULL AUTO_INCREMENT,
  `Fecha_evento` DATE NOT NULL,
  `Hora_Evento` DATETIME NOT NULL,
  `Anticipacion` DATETIME NOT NULL,
  `Detalle` VARCHAR(200) NOT NULL,
  `Es_Recurrente` TINYINT NOT NULL,
  PRIMARY KEY (`Id_Evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Solicitudes` (
  `Id_Solicitud` INT NOT NULL AUTO_INCREMENT,
  `Valor` INT NOT NULL,
  `Solicitante` VARCHAR(100) NOT NULL,
  `Detalle` VARCHAR(200) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Solicitar_a` VARCHAR(100) NOT NULL,
  `Tipo_Solicitud` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id_Solicitud`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado_Solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado_Solicitud` (
  `Id_Estado_Solicitud` INT NOT NULL AUTO_INCREMENT,
  `Pendiente` VARCHAR(100) NOT NULL,
  `Aprobado` VARCHAR(100) NOT NULL,
  `Rechazado` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id_Estado_Solicitud`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notificaciones` (
  `Id_Notificaciones` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Url_notificacion` VARCHAR(100) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Estado` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id_Notificaciones`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
